export default [
  {
    id : 'TripType',
    optionId: 1,
    value: 'I am looking for a romantic trip.',
    label: 'Yes! A romantic trip',
    message: 'Yes! A romantic trip',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'romantic',
    apiFlag: false,
    dynamicFlag: false,
    user: true
  },
  {
    id : 'TripType',
    optionId: 2,
    value: 'I am looking for a family trip.',
    label: 'Yes! For a family trip',
    message: 'Yes! For a family trip',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'family',
    apiFlag: false,
    dynamicFlag: false,
    user: true
  },
  {
    id : 'TripType',
    optionId: 3,
    value: 'I am looking for a honeymoon trip.',
    label: 'Yes! A honeymoon trip',
    message: 'Yes! A honeymoon trip',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'honeymoon',
    apiFlag: false,
    dynamicFlag: false,
    user: true
  },
  {
    id : 'TripType',
    optionId: 4,
    value: 'I am looking for a trip with my friends.',
    label: 'Yes! For a trip with my friends',
    message: 'Yes! For a trip with my friends',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'friends',
    apiFlag: false,
    dynamicFlag: true,
    user: true
  },
  {
    id : 'TripType',
    optionId: 5,
    value: 'I am looking for a group trip.',
    label: 'For a group trip',
    message: 'For a group trip',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'group',
    apiFlag: false,
    dynamicFlag: true,
    user: true
  },
  {
    id : 'TripType',
    optionId: 6,
    value: 'I am looking for a solo trip.',
    label: 'For a solo trip',
    message: 'For a solo trip',
    trigger: 'Assistance Type Module',
    rbtKey: 'tour',
    rbtValue: 'solo',
    apiFlag: false,
    dynamicFlag: true,
    user: true
  },
];
