const IconsMapping = {
  CabTransfer: 'CabTransfer',
  Drinks: 'DrinkIcon',
  Flight: 'FlightIcon',
  GooglePlay: 'GooglePlay',
  AppStore: 'AppStore',
  Meal: 'Meal',
  TTlogoSecondary: 'TTlogoSecondary',
  HouseBoat: 'HouseBoatIcon',
  SortIcon: 'SortIcon',
  FilterIcon: 'FilterIcon',
  IndianIcon: 'IndianIcon',
  InternationalIcon: 'InternationalIcon',
  IllusAgent: 'IllusAgent',
  IllusMoneySafe: 'IllusMoneySafe',
  IllusSupport: 'IllusSupport',
  IllusDestination: 'IllusDestination',
  LookingIcon: 'LookingIcon',
  CustomPackage: 'CustomPackage',
  ChatIcon: 'ChatIcon',
  ChatIconWhite: 'ChatIconWhite',
  CallUs: 'CallUs',
  CallBackIcon: 'CallBackIcon',
  Confusion: 'Confusion',
  Help: 'Help',
  FBIcon: 'FBIcon',
  GoogleIcon: 'GoogleIcon',
  LockIcon: 'LockIcon',
  TicketsIcon: 'TicketsIcon',
  ArrowNext: 'ArrowNext',
  CalendarIcon: 'CalendarIcon',
  BudgetIcon: 'BudgetIcon',
  CabIconFront: 'CabIconFront',
  NextIcon: 'NextIcon',
  CloseDark: 'CloseDark',
  IllusRequestCallback: 'IllusRequestCallback',
  Illus404: 'Illus404',
  IllusDestinationsOld: 'IllusDestinationsOld',
  IllusDestinations: 'IllusDestinations',
  IllusQualityCheck: 'IllusQualityCheck',
  IllusForgotPassword: 'IllusForgotPassword',
  IllusThanksRequest: 'IllusThanksRequest',
  AllTrips: 'AllTrips',
  Weekendmeal: 'Meal',
  Trekking: 'TrekkingIcon',
  Rafting: 'RaftingIcon',
  Paragliding: 'ParaIcon',
  Rockclimbing: 'RockClimbingIcon',
  Flyingfox: 'FlyingFoxIcon',
  Repelling: 'RepellingIcon',
  Bonfire: 'BonFireIcon',
  Music: 'MusicIcon',
  Dj: 'DJIcon',
  Jeepsafari: 'JeepIcon',
  Swimming: 'SwimmingPoolIcon',
  Photography: 'CameraIcon',
  Deluzeacbus: 'BusIcon',
  Tempotraveler: 'MinIBusIcon',
  Sharedcoach: 'BusIcon',
  Transport: 'MinIBusIcon',
  Luxurycamp: 'CampIcon',
  Eveningsnack: 'EveningSnacksIcon',
  Jumping: 'SkyDvieIcon',
  Prasailing: 'ParaSellingicon',
  Livemusic: 'MusicIcon',
  MealPlanforHotel: 'Meal',
  Meals: 'Meal',
  Hotel: 'HotelIcon',
  Sightseeing: 'SightseeingIcon',
  Cab: 'CabIconFront',
  SharedCoach: 'CabTransfer',
  Complimentarydrinks: 'DrinkIcon',
  Flights: 'FlightIcon',
  Houseboat: 'HouseBoatIcon',
  Cruise: 'CruiseIcon',
  JetSkiTransfer: 'JetSkiIcon',
  Safari: 'SafariIcon',
  Watersports: 'WaterActivities',
  Adventure: 'Adventure',
  Visa: 'VisaIcon',
  FerryTransfer: 'FerriIcon',
  Cake: 'CakeIcon',
  FloralDecoration: 'FloralDecorationIcon',
  Campstay: 'CampIcon',
  Entrytickets: 'TicketsIcon',
  HomeStay: 'HotelIcon',
  JeepSafari: 'JeepIcon',
  TreeHouse: 'TreeHouseIcon',
  Disneyland: 'DisneyLandIcon',
  ReligiousTour: 'ReligiousIcon',
  Transfer: 'CabTransfer',
  Simcard: 'SimCardIcon',
  CloseWhite: 'CloseWhite',
  NotificationBell: 'NotificationBell',
  ShareIcon: 'ShareIcon',
  PackageIcon: 'PackageIcon',
  CompareIcon2: 'CompareIcon2',
  CompareIconWhite: 'CompareIconWhite',
  Uniquerequirements: 'Uniquerequirements',
  Envelope: 'Envelope',
  ThankYouTick: 'ThankYouTick',
  Default: 'DefaultIcon',
  Activities: 'TrekkingIcon',
  AdoutDestinationIcon: 'AdoutDestinationIcon',
  AgentIcon: 'AgentIcon',
  AndroidIcon: 'AndroidIcon',
  AttachmentIcon: 'AttachmentIcon',
  Autumn: 'Autumn',
  BackIcon: 'BackIcon',
  Back2IconWhite: 'Back2IconWhite',
  BackTopArrow: 'BackTopArrow',
  BeachIconGrey: 'BeachIconGrey',
  BudgetIconNew: 'BudgetIconNew',
  BusIllus: 'BusIllus',
  CabIconFrontGrey: 'CabIconFrontGrey',
  CallUsWhite: 'CallUsWhite',
  CallUsWhiteFill: 'CallUsWhiteFill',
  Clock: 'Clock',
  ComparePackage: 'ComparePackage',
  CustomisedPackages: 'CustomisedPackages',
  DefaultIcon: 'DefaultIcon',
  DurationIcon: 'DurationIcon',
  EmiIcon: 'EmiIcon',
  ExclusionIcon: 'ExclusionIcon',
  Ferrytransfer: 'Ferrytransfer',
  FilterIconWhite: 'FilterIconWhite',
  Friends: 'Friends',
  GymIcon: 'GymIcon',
  HalfStar: 'HalfStar',
  HillStation: 'HillStationIcon',
  HillStationIcon: 'HillStationIcon',
  HillStationIconGrey: 'HillStationIconGrey',
  History: 'History',
  HotelEmptyState: 'HotelEmptyState',
  InclusionIcon: 'InclusionIcon',
  IndianIconGrey: 'IndianIconGrey',
  IOS: 'IOS',
  KeyboardActive: 'KeyboardActive',
  KeyboardInactive: 'KeyboardInactive',
  LinkedIn: 'LinkedIn',
  LockWhite: 'LockWhite',
  LoveIcon: 'LoveIcon',
  MailIconWhite: 'MailIconWhite',
  MessageIconNew: 'MessageIconNew',
  MobileIcon: 'MobileIcon',
  Monsoon: 'Monsoon',
  MountainIcon: 'MountainIcon',
  Nature: 'NatureIcon',
  NatureIcon: 'NatureIcon',
  NatureIconGrey: 'NatureIconGrey',
  NotificationIcon: 'NotificationIcon',
  PhoneIconWhite: 'PhoneIconWhite',
  PriceIcon: 'PriceIcon',
  Religious: 'ReligiousIcon',
  FriendsAndGroups: 'ReligiousIcon',
  RestaurantIcon: 'RestaurantIcon',
  RoomServiceIcon: 'RoomServiceIcon',
  SearchBlack: 'SearchBlack',
  Ship: 'Ship',
  StatusCrossIcon: 'StatusCrossIcon',
  StatusSuccessIcon: 'StatusSuccessIcon',
  StepArrow: 'StepArrow',
  Summer: 'Summer',
  TaxiCab: 'TaxiCab',
  Train: 'Train',
  TTIcon: 'TTIcon',
  TwitterGrey: 'TwitterGrey',
  Visa2: 'Visa',
  WaterActivities: 'WaterActivities',
  WaterActivitiesGrey: 'WaterActivitiesGrey',
  WeatherIcon: 'WeatherIcon',
  WifiIcon: 'WifiIcon',
  Winter: 'Winter',
  DiamondIcon: 'DiamondIcon',
  WebsiteIconNew: 'WebsiteIconNew',
  AirConditioningIcon: 'AirConditioningIcon',
  Bar: 'BarIcon',
  Beachaccess: 'BeachAccessIcon',
  FreeBreakfast: 'BreakfastIconNew',
  BusinessCenter: 'BusinessCentreIcon',
  HChildFriendly: 'ChildFriendlyIcon',
  EmailIcon: 'EmailIcon',
  Golfcourse: 'GolfIcon',
  Fitnesscenter: 'GymIconNew',
  HotTub: 'HotTubIcon',
  Kitcheninsomerooms: 'KitchenIcon',
  LaundryService: 'LaundryIcon',
  LocationIcon: 'LocationIcon',
  Freeparking: 'ParkingIcon',
  PetFriendly: 'PetFriendlyIcon',
  PhoneIcon: 'PhoneIcon',
  OutdoorPool: 'PoolIcon',
  Restaurant: 'RestaurantIconNew',
  RoomService: 'RoomServiceIconNew',
  AirportShuttle: 'ShuttleIcon',
  Smokefree: 'SmokeFreeIcon',
  Spa: 'SpaIcon',
  WalletIcon: 'WalletIcon',
  TTRecommendedIcon: 'TTRecommendedIcon',
  BulbIcon: 'BulbIcon',
  WhatsAppIcon: 'WhatsAppIcon',
  TajMahalIcon: 'TajMahalIcon',
  AdvantureIconNew: 'AdvantureIconNew',
  PlusInclusionIcon: 'PlusInclusionIcon',
  IntentExplore: 'IntentExplore',
  WhiteShareIcon: 'ShareWhite',
  LandlineIcon: 'LandlineIcon',
  DownloadVoucherIcon: 'DownloadVoucherIcon',
  EditPreferencesIcon: 'EditPreferencesIcon',
  HeadphoneIcon: 'HeadphoneIcon',
  HeadphoneIconWhite: 'HeadphoneIconWhite',
  ShareBlack: 'ShareBlack',
  NotificationIconWhite: 'NotificationIconWhite',
  DownloadBlack: 'DownloadBlack',
  DownloadBlue: 'DownloadBlue',
  IllusProgressB: 'IllusProgressB',
  GmailIcon: 'GmailIcon',
  DateDecided: 'DateDecided',
  DateNotDecided: 'DateNotDecided',
  BudgetLow: 'BudgetLow',
  BudgetMedium: 'BudgetMedium',
  BudgetHigh: 'BudgetHigh',
  Travelers: 'Travelers',
  Contact: 'Contact',
  Destination: 'Destination',
  LeftRedArrow: 'LeftRedArrow',
  RightWhiteArrow: 'RightWhiteArrow',
  DisabledArrowLeft: 'DisabledArrowLeft',
  HotelFilled: 'HotelFilled',
  FlightFilled: 'FlightFilled',
  CabsFilled: 'CabsFilled',
  BudgetMin: 'BudgetMin',
  Tick: 'Tick',
  PartPay: 'PartPay',

  // QDP new Icons
  RequestIcon: 'RequestIcon',
  PreferencesIcon: 'PreferencesIcon',
  InclusionsNewIcon: 'InclusionsNewIcon',
  ExclusionsNewIcon: 'ExclusionsNewIcon',
  TnCIcon: 'TnCIcon',
  InfoBlackIcon: 'InfoBlackIcon',
  ItineraryIcon: 'ItineraryIcon',
  TravelInfoIcon: 'TravelInfoIcon',
  SuccessIllustration: 'SuccessIllustration',
  BriefcaseWhiteIcon: 'BriefcaseWhiteIcon',
  FamilyWhiteIcon: 'FamilyWhiteIcon',
  HoneymoonWhiteIcon: 'HoneymoonWhiteIcon',
  TriangleIcon: 'TriangleIcon',
  ProgressIcon: 'ProgressIcon',
  ProcessedIcon: 'ProcessedIcon',
  EnvelopeIcon: 'EnvelopeIcon',
  PlayIcon: 'PlayIcon',
  CompareIcon: 'CompareIcon',
  ChatIconGrey: 'ChatIconGrey',
  LuxuryPackageIcon: 'LuxuryPackageIcon',
  BlackShareIcon: 'Black-share-icon',
  QuotesReceivedIcon: 'QuotesReceivedIcon',
  NoQuotesReceivedIcon: 'NoQuotesReceivedIcon',
  OutlineStarIcon: 'OutlineStarIcon',
  FillStarIcon: 'FillStarIcon',
  QualityQuotesIcon: 'QualityQuotesIcon',
  RightGreyArrow: 'RightGreyArrow',
  CloseIconWhite: 'CloseIconWhite',
  CrossRed: 'CrossRed',
  GreenTickInclusion: 'GreenTickInclusion',
  ExclusionsRed: 'ExclusionsRed',
  PriceRupee: 'PriceRupee',
  WaveIcon: 'WaveIcon',
  MktAgents: 'MktAgents',
  MktDestinations: 'MktDestinations',
  MktVerified: 'MktVerified',
  MktQualityControl: 'MktQualityControl',
  MktSupport: 'MktSupport',
  MktSelectPackage: 'MktSelectPackage',
  MktQuotes: 'MktQuotes',
  MktTravelers: 'MktTravelers',
  ProfileIcon2: 'ProfileIcon2',


  //amp icons
  IllusTraveler: 'IllusTraveler',
  PdpQuotes: 'PdpQuotes',
  PdpSelectPackage: 'PdpSelectPackage',
  DownArrow: 'DownArrow',
  StarIcon: 'StarIcon',
  StarIconEmpty: 'StarIconEmpty',
  Back2Icon: 'Back2Icon',
  InfoIcon: 'InfoIcon',
  SearchIcon: 'SearchIcon',
  TTlogo: 'TTlogo',
  ShareWhite: 'ShareWhite',
  ProfileIcon: 'ProfileIcon',
  HomeIcon: 'HomeIcon',
  FamilyIcon: 'FamilyIcon',
  WorkIcon: 'WorkIcon',
  OffersIcon: 'OffersIcon',
  BlogIcon: 'BlogIcon',
  TestimonailsIcon: 'TestimonailsIcon',
  FAQIcon: 'FAQIcon',
  ContactIcon: 'ContactIcon',
  VactionIcon: 'VactionIcon',
  HoneymoonPackages: 'HoneymoonPackages',
  SeasonalIcon: 'SeasonalIcon',
  InternationalIconBlack: 'InternationalIconBlack',
  LocationMarkerIcon: 'LocationMarkerIcon',
  FBIconWhite: 'FBIconWhite',
  Twitter: 'Twitter',
  PinterestIcon: 'PinterestIcon',
  GoogleIconWhite: 'GoogleIconWhite',
  Instagram: 'Instagram',
  BlueDownArrow: 'BlueDownArrow',
  GreenTick: 'GreenTick',



};

export default IconsMapping;

// const ampIconMappings = {
//   IllusTraveler: 'IllusTraveler',
//   PdpQuotes: 'PdpQuotes',
//   PdpSelectPackage: 'PdpSelectPackage',
//   DownArrow: 'DownArrow',
//   StarIcon: 'StarIcon',
//   StarIconEmpty: 'StarIconEmpty',
//   Back2Icon: 'Back2Icon',
//   InfoIcon: 'InfoIcon',
//   SearchIcon: 'SearchIcon',
//   TTlogo: 'TTlogo',
//   ShareWhite: 'ShareWhite',
//   ProfileIcon: 'ProfileIcon',
//   HomeIcon: 'HomeIcon',
//   FamilyIcon: 'FamilyIcon',
//   WorkIcon: 'WorkIcon',
//   OffersIcon: 'OffersIcon',
//   BlogIcon: 'BlogIcon',
//   TestimonailsIcon: 'TestimonailsIcon',
//   FAQIcon: 'FAQIcon',
//   ContactIcon: 'ContactIcon',
//   VactionIcon: 'VactionIcon',
//   HoneymoonPackages: 'HoneymoonPackages',
//   SeasonalIcon: 'SeasonalIcon',
//   InternationalIconBlack: 'InternationalIconBlack',
//   LocationMarkerIcon: 'LocationMarkerIcon',
//   FBIconWhite: 'FBIconWhite',
//   Twitter: 'Twitter',
//   PinterestIcon: 'PinterestIcon',
//   GoogleIconWhite: 'GoogleIconWhite',
//   Instagram: 'Instagram',
//   BlueDownArrow: 'BlueDownArrow',
//   GreenTick: 'GreenTick',
// };
