export default Object.freeze({
  BOOK_NOW: 'BOOK_NOW',
  REJECT_QUOTE: 'REJECT_QUOTE',
  REACTIVATE_QUOTE: 'REACTIVATE_QUOTE',
  REQUEST_CALLBACK: 'REQUEST_CALLBACK',
  WAIT_FOR_INVOICE: 'WAIT_FOR_INVOICE',
  PAY_NOW: 'PAY_NOW',
});
