const SLIDER_1 = 1;
const SLIDER_2 = 2;
const SLIDER_3 = 3;
const DEALS = 'DEALS';
const VARIATION_1 = 'VARIATION_1';
const VARIATION_2 = 'VARIATION_2';
const VARIATION_3 = 'VARIATION_3';
const FORM_ONE_PART_ONE = 'FORM_ONE_PART_ONE';
const FORM_ONE_PART_TWO = 'FORM_ONE_PART_TWO';
const SEQUENTIAL_FORM_ONE = 'SEQUENTIAL_FORM_ONE';
const SEQUENTIAL_FORM_TWO = 'SEQUENTIAL_FORM_TWO';
const SEQUENTIAL_FORM_THREE = 'SEQUENTIAL_FORM_THREE';
const SEQUENTIAL_FORM_FOUR = 'SEQUENTIAL_FORM_FOUR';
const SEQUENTIAL_FORM_FIVE = 'SEQUENTIAL_FORM_FIVE';
const SEQUENTIAL_FORM_SIX = 'SEQUENTIAL_FORM_SIX';
const SEQUENTIAL_FORM_SEVEN = 'SEQUENTIAL_FORM_SEVEN';
const SEQUENTIAL_FORM_END = 'SEQUENTIAL_FORM_END';
const adminCommentsHashTag = '#slider_organic';
const formFilledOn = '#Form_filled_on';
const publicProductHashTag = '#pp_desktop';
const UPDATE_REDIS_KEY = 'updateFields/UPDATE_REDIS_KEY';
const UPDATE_TO_DESTINATION = 'updateFields/UPDATE_TO_DESTINATION';
const SET_DISPLAY_MODE = 'updateFields/SET_DISPLAY_MODE';
const UPDATE_FIELD = 'updateFields/UPDATE_FIELD';
const NEXT_SLIDE = 'nextSlide';
const PREV_SLIDE = 'prevSlide';
const ENABLED_FOR_SUBMIT = 'slider/ENABLED_FOR_SUBMIT';
const SLIDER_2_SUBMIT = 'slider_2_submit';
const TITLE = {
  1: 'Your Preferences',
  2: 'Great! Tell Us What You Prefer',
  3: 'Almost Done!'
};
const TRIP_UPDATED_IN_REDIS = "updateFields/TRIP_UPDATED_IN_REDIS";

export {
  SLIDER_1,
  SLIDER_2,
  SLIDER_3,
  adminCommentsHashTag,
  formFilledOn,
  publicProductHashTag,
  UPDATE_REDIS_KEY,
  UPDATE_TO_DESTINATION,
  SET_DISPLAY_MODE,
  UPDATE_FIELD,
  NEXT_SLIDE,
  PREV_SLIDE,
  ENABLED_FOR_SUBMIT,
  SLIDER_2_SUBMIT,
  TITLE,
  VARIATION_1,
  VARIATION_2,
  VARIATION_3,
  FORM_ONE_PART_ONE,
  FORM_ONE_PART_TWO,
  SEQUENTIAL_FORM_ONE,
  SEQUENTIAL_FORM_TWO,
  SEQUENTIAL_FORM_THREE,
  SEQUENTIAL_FORM_FOUR,
  SEQUENTIAL_FORM_FIVE,
  SEQUENTIAL_FORM_SIX,
  SEQUENTIAL_FORM_SEVEN,
  SEQUENTIAL_FORM_END,
  TRIP_UPDATED_IN_REDIS,
  DEALS
};
