/* eslint-disable max-len */
import config from 'appConfig';

const honeymoonData = [
  {
    "tripId": 1280077,
    "tripType": "Honeymoon",
    "tagName": "Neha's romantic adventure",
    "heading": "Neha's Recipe For A Perfect Bali Honeymoon",
    "tags": "#love, #thrill, #adventure, #peace",
    "description": "Neha shares her epic Bali experience with us. She elaborates on her romantic beach walks with her husband, their underwater adventures, shopping & a host of things that made their honeymoon a success.",
    "travellerName": "Neha Jadhav",
    "travellerLocation": "Mumbai",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Bali",
    "link": "https://traveltriangle.com/blog/neha-romantic-things-to-do-in-bali-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/ThumbNail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0003.jpg`,
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0011.jpg`,
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0012.jpg`,
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0013.jpg`,
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0018.jpg`,
      `${config.assets.images}/public-product/Travelogues/Neha+Jadhav/Copy+of+IMG-20170722-WA0039.jpg`
    ]
  },
  {
    "tripId": 1588185,
    "tripType": "Honeymoon",
    "tagName": "Nishant's Mauritius vacation",
    "heading": "Nishant's King-Size Vacation In Mauritius",
    "tags": "#luxury, #adventure, #beach, #romantic",
    "description": "Beaches, nature parks & water sports made Nishant's luxury vacation in Mauritius with his wife an affair to remember. He shares their impeccable experience through pictures that would make you go wow!",
    "travellerName": "Nishant Raj",
    "travellerLocation": "New Delhi",
    "daysAgo": "1 day ago",
    "stars": 4,
    "destination": "Trip to Mauriitus",
    "link": "https://traveltriangle.com/blog/nishant-luxury-vacation-in-mauritius-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+day+1+ile+aux+cerf.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+day+2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+day+4+volcano.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+DSC_0075.png`, `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+DSC_0522.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+IMG_9745.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nishant+Raj/Copy+of+seewalk.jpg`
    ]
  },
  {
    "tripId": 1326286,
    "tripType": "Honeymoon",
    "tagName": "Akash's luxurious honeymoon",
    "heading": "Akash's Ultra Luxurious Honeymoon In Maldives",
    "tags": "#honeymoon, #luxury, #adventure, #beauty",
    "description": "Akash and his wife chose Centara Ras Fushi as their private island resort on their honeymoon in Maldives. They tell us why it is an excellent pick for couples who want the best of romance &  adventure.",
    "travellerName": "Akash & Toshi",
    "travellerLocation": "Bhopal",
    "daysAgo": "2 days ago",
    "stars": 5,
    "destination": "Trip to Maldives",
    "link": "https://traveltriangle.com/blog/akash-honeymoon-trip-to-maldives-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/Thumbnail+Image.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/p1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/p2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/p3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/p4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Aakash+%26+Toshi/p5.jpg`
    ]
  },
  {
    "tripId": 1556919,
    "tripType": "Honeymoon",
    "tagName": "Kanav's Singapore Bali honeymoon",
    "heading": "Kanav's Epic Singapore And Bali Honeymoon",
    "tags": "#honeymoon, #romantic, #luxury, #adventure",
    "description": "Kanav & his wife witnessed the best of two worlds on their Singapore & Bali honeymoon. On their first international trip, Kanav shares how they relished every bit of an urban, and a tropical paradise!",
    "travellerName": "Kanav Puri",
    "travellerLocation": "Amritsar",
    "daysAgo": "2 days ago",
    "stars": 5,
    "destination": "Trip to Singapore & Bali",
    "link": "https://traveltriangle.com/blog/kanav-singapore-bali-honeymoon-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Kanav/Thumbnail+Image.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Kanav/K1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Kanav/k2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Kanav/k3.png`, `${config.assets.images}/public-product/Travelogues/Kanav/k4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Kanav/k5.jpg`
    ]
  },
  {
    "tripId": 1202432,
    "tripType": "Honeymoon",
    "tagName": "Hemant's Romantic holiday in Maldives",
    "heading": "Hemant's Impeccable Honeymoon In Maldives ",
    "tags": "#honeymoon, #adventure, #beach, #nature",
    "description": "Hemant and his wife started their new life with a honeymoon in Maldives & their experience will leave you in awe. From romantic beach walks to fun water sports, here's how they made the most out of it.",
    "travellerName": "Hemant Lamoriya",
    "travellerLocation": "New Delhi",
    "daysAgo": "3 days ago",
    "stars": 5,
    "destination": "Trip to Maldives",
    "link": "https://traveltriangle.com/blog/hemant-honeymoon-trip-to-maldives-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0000.jpg`,
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0003.jpg`,
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0009.jpg`,
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0010.jpg`,
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0013.jpg`,
      `${config.assets.images}/public-product/Travelogues/Hemant+Lamoriya/Copy+of+IMG-20170403-WA0014.jpg`
    ]
  },
  {
    "tripId": 1337831,
    "tripType": "Honeymoon",
    "tagName": "Sohel's Vietnam visit with wife",
    "heading": "Sohel's Romantic Adventure In Vietnam",
    "tags": "#romantic, #adventure, #wanderlust, #companionship",
    "description": "Sohel and his wife experience romance from a different angle as they go on an epic trip exploring the many wonders of Vietnam. They tell us how this incredible journey changed them for better!",
    "travellerName": "Sohel Devani",
    "travellerLocation": "Hyderabad",
    "daysAgo": "3 days ago",
    "stars": 4,
    "destination": "Trip to Vietnam ",
    "link": "https://traveltriangle.com/blog/sohel-romantic-trip-to-vietnam-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Thumbnail+image.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+1_Hanoi.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+1_Nha+Tarang.JPG+100.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+2_HaLong+Bay.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+2_Hanoi.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+3_HaLong+Bay.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sohel+Devani/Copy+of+4_Nha+Tarang.jpg`
    ]
  },
  {
    "tripId": 1161252,
    "tripType": "Honeymoon",
    "tagName": "Sairam's one-of-its-kind honeymoon",
    "heading": "Sairam's Heavenly Honeymoon In Bali ",
    "tags": "#honeymoon, #adventure, #nature, #luxury",
    "description": "A perfect blend of romance, nature & adventure, Sairam's honeymoon in Bali was heavenly. From the sunset dinner cruise to the Kintamani tour, here are all the secrets behind their memorable affair. ",
    "travellerName": "Sairam Menon",
    "travellerLocation": "Hyderabad",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Bali",
    "link": "https://traveltriangle.com/blog/sairam-5n-6d-honeymoon-in-bali-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Copy+of+day1_IMG_5622.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Copy+of+day2_DSC1982.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Copy+of+day2_DSC2010.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Copy+of+day3_IMG_5352.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sairam+Menon/Copy+of+day5_IMG_6275.jpg`
    ]
  },
  {
    "tripId": 1127006,
    "tripType": "Honeymoon",
    "tagName": "Double delight honeymoon",
    "heading": "Gurpreet's Honeymoon In Singapore And Bali",
    "tags": "#honeymoon, #nature, #sightseeing, #beach",
    "description": "Having visited both Singapore and Bali on his honeymoon, Gurpreet tells us about the best places to visit in both the countries for a fruitful romantic experience with your special one.",
    "travellerName": "Gurpreet Bhatia",
    "travellerLocation": "New Delhi",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Singapore & Bali",
    "link": "https://traveltriangle.com/blog/gurpreet-honeymoon-trip-to-singapore-and-bali-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Copy+of+IMG-20170320-WA0011.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Copy+of+IMG-20170320-WA0043.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Copy+of+IMG-20170320-WA0068.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Copy+of+IMG-20170320-WA0082.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Bhatia/Copy+of+IMG-20170320-WA0086.jpg`
    ]
  },
  {
    "tripId": 1823982,
    "tripType": "Honeymoon",
    "tagName": "Falak's Romantic Holiday In Europe",
    "heading": "Falak's Venetian Holiday With His Wife",
    "tags": "#Romantic, #Nature, #Historical, #Mountains",
    "description": "Falak and his wife experienced old-world romance on their European holiday. From the iconic Eiffel Tower to the snowy mountains of Switzerland to the Gondola ride in Venice, they indulged in all.",
    "travellerName": "Falak Pandya",
    "travellerLocation": "Bangalore",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Europe",
    "link": "https://traveltriangle.com/blog/falak-romantic-trip-to-europe-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Thumbnail/Gondola+ride+in+Venice+.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Falak+Pandya+(Europe)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1042770,
    "tripType": "Honeymoon",
    "tagName": "The Most Special Honeymoon In Europe",
    "heading": "Akshay's Surreal Honeymoon In Europe",
    "tags": "#Romantic, #Nature, #Historical, #Mountains",
    "description": "Akshay's honeymoon in Europe was a holiday of a lifetime! They witnessed the heavenly mountains of Switzerland and old world charm of Italy on a special holiday that will stay in their hearts forever!",
    "travellerName": "Akshay Punjabi",
    "travellerLocation": "Delhi",
    "daysAgo": "2 day ago",
    "stars": 5,
    "destination": "Trip to Europe",
    "link": "https://traveltriangle.com/blog/akshay-romantic-trip-to-europe-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Thumbnail/IMG-20170204-WA0035.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Akshay+Punjabi+(Europe)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1837318,
    "tripType": "Honeymoon",
    "tagName": "Pankaj's Exotic Honeymoon In Bali",
    "heading": "Pankaj's Utterly Exotic Honeymoon In Bali",
    "tags": "#Romantic, #Beaches, #Adventure, #Nature",
    "description": "From temples to beaches, and from nature to adventure, Pankaj and his wife wanted to experience the best of an exotic destination and here's how Bali surprised them beyond their expectations!",
    "travellerName": "Pankaj Verma",
    "travellerLocation": "Delhi",
    "daysAgo": "2 day ago",
    "stars": 4,
    "destination": "Trip to Bali",
    "link": "https://traveltriangle.com/blog/pankaj-honeymoon-trip-to-bali-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Thumbnail/IMG_20171013_174531.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pankaj+Verma+(Bali)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1835275,
    "tripType": "Honeymoon",
    "tagName": "A Magnificent Greek Honeymoon",
    "heading": "Sonali's Mediterranean Romantic Trip To Greece",
    "tags": "#Sea, #Romantic, #Beach, #Nightlife",
    "description": "Sonali and her husband went on a glamorous romantic trip to Greece and it was truly special in every manner. They enjoyed the magnificent charm of the Aegean Sea and the old-world charm of Santorini.",
    "travellerName": "Sonali Mahajan",
    "travellerLocation": "Mumbai",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Europe",
    "link": "https://traveltriangle.com/blog/sonali-romantic-trip-to-greece-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Thumbnail/IMG-20171105-WA0069.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sonali+Mahajan+(Europe)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1297978,
    "tripType": "Honeymoon",
    "tagName": "Tale Of Romance In Seychelles",
    "heading": "Rajnish's Action-Packed Seychelles Honeymoon",
    "tags": "#Romantic, #Beaches, #Adventure, #Nature",
    "description": "Rajnish's honeymoon in Seychelles was the perfect blend of romance and adventure. From exploring the islands on their own to having beachside dinner dates, see how they made their trip ultra romantic.",
    "travellerName": "Rajnish Kumar",
    "travellerLocation": "Mumbai",
    "daysAgo": "2 day ago",
    "stars": 4,
    "destination": "Trip to Seychelles",
    "link": "https://traveltriangle.com/blog/rajnish-seychelles-honeymoon-tour-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Thumbnail/La+digue.JPG`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Rajnish+Kumar+(Seychelles)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 878988,
    "tripType": "Honeymoon",
    "tagName": "Adventurous Honeymoon In Maldives",
    "heading": "Nisarg's Adventurous Honeymoon In Maldives",
    "tags": "#Romantic, #Beaches, #Adventure, #Nature",
    "description": "Nisarg & his wife had a picture-perfect honeymoon in Maldives. Here's how they indulged in adventurous experiences, explored the island at their own pace, and had the dream vacation of their lives.",
    "travellerName": "Nisarg Patel",
    "travellerLocation": "Mumbai",
    "daysAgo": "2 day ago",
    "stars": 5,
    "destination": "Trip to Maldives",
    "link": "https://traveltriangle.com/blog/nisargs-honeymoon-trip-to-maldives-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Thumbnail/image006.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nisarg+Patel+(Maldives)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1879168,
    "tripType": "Honeymoon",
    "tagName": "Nitin's Romantic Holiday In Maldives",
    "heading": "Nitin's Romantic Escape To Maldives",
    "tags": "#Romantic, #Nature, #Beaches, #Luxury",
    "description": "Nitin & his wife's love for travel made them take a romantic trip to Maldives. They share with us their beautiful memories and how this holiday offered them the perfect privacy, comfort & happiness.",
    "travellerName": "Nitin Parekh",
    "travellerLocation": "Mumbai",
    "daysAgo": "2 day ago",
    "stars": 4,
    "destination": "Trip to Maldives",
    "link": "https://traveltriangle.com/blog/nitin-things-to-do-on-a-romantic-trip-to-maldives-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Thumbnail/DSC_2410.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitin+Parekh+(Maldives)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1767226,
    "tripType": "Honeymoon",
    "tagName": "Exploring The Beauty Of Ladakh",
    "heading": "Nitish's Picture Perfect Trip To Ladakh",
    "tags": "#Nature, #Adventure, #Romantic, #Cultural",
    "description": "Nitish and his wife went on a surreal journey to Ladakh and witnessed the magic of nature like never before. From visiting famous lakes to indulging in the culture, it was a once in a lifetime journey.",
    "travellerName": "Nitish Agrawal",
    "travellerLocation": "Pune",
    "daysAgo": "1 day ago",
    "stars": 4,
    "destination": "Trip to Ladakh",
    "link": "https://traveltriangle.com/blog/nitish-romantic-trip-to-ladakh-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/thumbnail/image021.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Nitesh+(Ladakh)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 2302111,
    "tripType": "Honeymoon",
    "tagName": "Ankit's perfect maldives honeymoon",
    "heading": "Water Villas, Candlelight Dinners, Cruises & Spa: A Perfect Honeymoon",
    "tags": "#love, #peace, #relax, #chill",
    "description": "All they wanted was to spend time with each other and simply relax amid some " +
    "gorgeous backdrops. So, Ankit booked himself and his wife Priya a fabulous 4 nights 5 days Maldives honeymoon package.",
    "travellerName": "Ankit Wadhwa",
    "travellerLocation": "New Delhi",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Maldives",
    "link": "https://traveltriangle.com/blog/ankit-and-priya-honeymoon-trip-to-maldives-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/77.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Ankit+Wadhwa/6.jpg`
    ]
  }
];

const familyData = [
  {
    "tripId": 1745941,
    "tripType": "Family",
    "tagName": "Seema's adventure trip",
    "heading": "Seema's Andaman Holiday With Family & Friends",
    "tags": "#family, #adventure, #beach, #nature",
    "description": "From watching the light & sound show at the Cellular Jail to beach hopping, Seema saw her dream of witnessing Andaman at its best come true. She shares the sweet tales from her trip and you'll love it.",
    "travellerName": "Seema Kumar",
    "travellerLocation": "New Delhi",
    "daysAgo": "3 days ago",
    "stars": 5,
    "destination": "Trip to Andaman",
    "link": "https://traveltriangle.com/blog/seema-trip-with-family-friends-to-andaman-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Copy+of+At+Havelock+beach.jpg`,
      `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Copy+of+At+Kaala+Patthar+beach.jpg`,
      `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Copy+of+Fishermen+at+Havelock+beach.jpg`,
      `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Copy+of+IMG_20170719_143610024.jpg`,
      `${config.assets.images}/public-product/Travelogues/Seema+Kumar/Copy+of+On+way+to+snorkelling1.jpg`
    ]
  },
  {
    "tripId": 1180351,
    "tripType": "Family",
    "tagName": "A mother's trip to Iceland",
    "heading": "Pooja's Marvelous Family Trip To Iceland",
    "tags": "#family, #nature, #snow, #bonding",
    "description": "Pooja went on a family holiday to Iceland and Norway with her parents and daughter. She tells us how the trip was a mind blowing experience for them why both the countries are a must visit for all. ",
    "travellerName": "Pooja Nahar",
    "travellerLocation": "Mumbai",
    "daysAgo": "1 day ago",
    "stars": 4,
    "destination": "Trip to Europe",
    "link": "https://traveltriangle.com/blog/pooja-family-trip-to-iceland-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Copy+of+IMG-20170524-WA0078.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Copy+of+IMG-20170524-WA0080.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Copy+of+IMG-20170524-WA0094.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Copy+of+IMG-20170524-WA0102.jpg`,
      `${config.assets.images}/public-product/Travelogues/Pooja+Nahar/Copy+of+IMG-20170524-WA0122.jpg`
    ]
  },
  {
    "tripId": 1501803,
    "tripType": "Family",
    "tagName": "Megha's Sikkim Trip",
    "heading": "Megha's Fun Family Trip To Sikkim & Darjeeling",
    "tags": "#family, #nature, #adventure, #sightseeing",
    "description": "Good companions make any holiday more memorable, and Megha's family trip to Sikkim & Darjeeling is a proof of that. From visiting the lakes to yak riding, here's how they had their moments of adventure.",
    "travellerName": "Megha Gupta",
    "travellerLocation": "Patna",
    "daysAgo": "2 days ago",
    "stars": 5,
    "destination": "Trip to Sikkim Darjeeling",
    "link": "https://traveltriangle.com/blog/megha-family-trip-to-sikkim-and-darjeeling-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Copy+of+B612_20170523_080830.jpg`,
      `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Copy+of+Mirik+(1).jpg`,
      `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Copy+of+Seven+Sister+(1).jpg`,
      `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Copy+of+Yumthang+(2).jpg`,
      `${config.assets.images}/public-product/Travelogues/Megha+Gupta/Copy+of+Zero+point+(1).jpg`
    ]
  },
  {
    "tripId": 1558634,
    "tripType": "Family",
    "tagName": "Couple's trip with daughter",
    "heading": "Heena's High On Love & Life Trip To Thailand",
    "tags": "#family, #culture, #nature, #luxury",
    "description": "For Heena & her husband, their trip to Thailand was more of a celebration of their daughter's happiness. Full of love & laughter, Heena shares how they celebrated their daughter's birthday in style!",
    "travellerName": "Heena Rajput",
    "travellerLocation": "New Delhi",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Thailand",
    "link": "https://traveltriangle.com/blog/heena-family-trip-to-thailand-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Copy+of+IMG-20170623-WA0001.jpg`,
      `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Copy+of+IMG-20170623-WA0002.jpg`,
      `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Copy+of+IMG-20170623-WA0005.jpg`,
      `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Copy+of+IMG-20170623-WA0045.jpg`,
      `${config.assets.images}/public-product/Travelogues/Heena+Rajput/Copy+of+IMG-20170623-WA0064.jpg`
    ]
  },
  {
    "tripId": 1472855,
    "tripType": "Family",
    "tagName": "Punita & Friends in Jaisalmer",
    "heading": "Punita's Trip To The Golden City With Friends",
    "tags": "#family, #friends, #adventure, #sightseeing",
    "description": "Punita and her friends went on a trip to Jaisalmer to explore the marvels of the city and its sand dunes. She shares her rich experiences with us and tell us why it's a perfect place for youngsters.",
    "travellerName": "Punita",
    "travellerLocation": "New Delhi",
    "daysAgo": "3 days ago",
    "stars": 4,
    "destination": "Trip to Rajasthan",
    "link": "https://traveltriangle.com/blog/punita-friends-trip-to-jaisalmer-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Copy+of+17.jpg`,
      `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Copy+of+2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Copy+of+34.jpg`,
      `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Copy+of+8.jpg`,
      `${config.assets.images}/public-product/Travelogues/Punita+Sharma/Copy+of+9.jpg`
    ]
  },
  {
    "tripId": 883902,
    "tripType": "Family",
    "tagName": "With family in Singapore & Malaysia",
    "heading": "Gurpreet's Family Trip To Singapore & Malaysia",
    "tags": "#family, #nature, #adventure, #sightseeing",
    "description": "Gurpreet's fun-loaded family trip to Singapore and Malaysia was exciting beyond limits. His family bonded stronger and better with time, and here's what Gurpreet wrote about his blissful vacation!",
    "travellerName": "Gurpreet Singh Gujral",
    "travellerLocation": "New Delhi",
    "daysAgo": "3 days ago",
    "stars": 5,
    "destination": "Trip to Singapore & Malaysia",
    "link": "https://traveltriangle.com/blog/gurpreet-family-trip-singapore-and-malaysia-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Copy+of+IMG-20161201-WA0001.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Copy+of+IMG-20161201-WA0008.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Copy+of+IMG-20161202-WA0015.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Copy+of+IMG-20161202-WA0023.jpg`,
      `${config.assets.images}/public-product/Travelogues/Gurpreet+Singh+Gujral/Copy+of+IMG-20161202-WA0065.jpg`
    ]
  },
  {
    "tripId": 1314705,
    "tripType": "Family",
    "tagName": "Fun-filled New Zealand Vacation",
    "heading": "Vikram's Restoring Family Trip To New Zealand",
    "tags": "#adventure, #nature, #luxury, #culture",
    "description": "Vikram went on an epic trip to New Zealand with his family & friends to relish the best of nature, and adventure. From cruising to helicopter rides, here's what Vikram wrote about his refreshing trip!",
    "travellerName": "Vikram Bellur",
    "travellerLocation": "Bengaluru",
    "daysAgo": "1 day ago",
    "stars": 4,
    "destination": "Trip to New Zealand",
    "link": "https://traveltriangle.com/blog/vikram-friends-family-trip-to-newzealand-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/Thumbnail.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/DSC_0989.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/DSC_0994.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/DSC_1847.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/DSC_2052.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/DSC_2187.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vikram+Bellur/IMG_20170414_141352.jpg+100.jpg`
    ]
  },
  {
    "tripId": 1487273,
    "tripType": "Family",
    "tagName": "Karthik's Fun Trip With Family",
    "heading": "Karthik's Incredible Family Trip To Langkawi",
    "tags": "#adventure, #family, #beach, #luxury",
    "description": "Of nature, adventure, & luxury, Karthik's fun-filled family trip to Langkawi was an out-of-the-world experience. From island hopping to skywalking, he shares how Langkawi cast a magical spell on them!",
    "travellerName": "Karthik Venkat",
    "travellerLocation": "New Delhi",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Langkawi",
    "link": "https://traveltriangle.com/blog/karthik-family-trip-to-langkawi-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Thumbnail+Image.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+IMG_20170608_175749.jpg`,
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+IMG_20170610_103618.jpg`,
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+IMG_20170610_121319.jpg`,
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+IMG_20170611_194018.jpg`,
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+IMG_20170611_194147.jpg`,
      `${config.assets.images}/public-product/Travelogues/Karthik+Venkat/Copy+of+original_efd8259d-f884-4e92-a10f-3d684293fabf_IMG_20170611_194237.jpg`
    ]
  },
  {
    "tripId": 1765284,
    "tripType": "Family",
    "tagName": "Sulabh's Family Holiday In Seychelles",
    "heading": "Sulabh's Adorable Seychelles Family Getaway",
    "tags": "#Nature, #Beaches, #Family, #Luxury",
    "description": "Sulabh and his adorable family had the most refreshing holiday experience in Seychelles. From scaling breathtaking beaches to hiking amid lush greens, here's what they did on their leisurely vacation.",
    "travellerName": "Sulabh Chandola",
    "travellerLocation": "Mumbai",
    "daysAgo": "3 day ago",
    "stars": 5,
    "destination": "Trip to Seychelles",
    "link": "https://traveltriangle.com/blog/sulabh-family-trip-to-seychelles-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Thumbnail/Cot+d'or+Beach.JPG`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Sulabh+Chandola+(Seychelles)/Best+6+(cropped)/6.jpg`
    ]
  },
  {
    "tripId": 1196658,
    "tripType": "Family",
    "tagName": "Fun Family Holiday In Hong Kong",
    "heading": "Vivek's Fun-Filled Family Trip To Hong Kong",
    "tags": "#Adventure, #Fun, #Luxury, #Beaches",
    "description": "Vivek took his wife & kids for a fun-filled holiday to Hong Kong, where they had the time of their lives. Here's how their day out in Disneyland made their trip more memorable and adventuresome.",
    "travellerName": "Vivek Bhaskar",
    "travellerLocation": "Delhi",
    "daysAgo": "1 day ago",
    "stars": 5,
    "destination": "Trip to Hong Kong",
    "link": "https://traveltriangle.com/blog/vivek-4-night-5-day-family-trip-to-hong-kong-travelogue/",
    "avatarPic": `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Thumbnail/IMG-20170107-WA0016.jpg`,
    "images": [
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/1.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/2.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/3.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/4.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/5.jpg`,
      `${config.assets.images}/public-product/Travelogues/Vivek+Bhaskar+(Hong+Kong)/Best+6+(cropped)/6.jpg`
    ]
  }
];

export default [...honeymoonData, ...familyData];
